permalink: /:year/:month/:day/:title/

markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false  

# Markdown 处理器
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

##Site
title: "Know thyself"
author: "liushoukai"
keywords: "博客，Jekyll"
description: "KAY个人博客"
baseurl: ""


links:
  - github: "https://github.com/liushoukai/"

excerpt_separator: "\n\n\n"

analytics:
  provider: google
  google: 
    tracking_id: 'UA-70311570-1' 

defaults:
  - scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Kay

paginate: 10
paginate_path: ":num"
