timezone: Asia/Shanghai

url: "https://liushoukai.github.io"
#baseurl: "/blog"
baseurl: ""

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "webpack", "webpack.config.js", "package.json", "package-lock.json", "scripts/"]

# Serving
detach: false
host: 0.0.0.0
port: 4000
show_dir_listing: false

##############
permalink: /:year/:month/:day/:title/

markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM

##Site
title: "Know thyself"
author: "liushoukai"
keywords: "博客，Jekyll"
description: "KAY个人博客"


links:
  - github: "https://github.com/liushoukai/"

excerpt_separator: "\n\n\n"

analytics:
  provider: google
  google:
    tracking_id: 'UA-70311570-1'

defaults:
  - scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Kay

paginate: 10
paginate_path: ":num"
