
url: "https://liushoukai.github.io"
#baseurl: "/blog"
baseurl: ""

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "webpack",
  "webpack.config.js",
  "package.json",
  "package-lock.json",
  "scripts/"
]

# Serving
detach: false
host: 0.0.0.0
port: 4000
show_dir_listing: false

##############

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false


##Site
title: "Know thyself"
author: "Kay"
keywords: "博客，Jekyll"
description: "KAY个人博客"


links:
  - github: "https://github.com/liushoukai/"

excerpt_separator: "\n\n\n"

analytics:
  provider: google
  google:
    tracking_id: 'UA-70311570-1'

defaults:
  - scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Kay

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: /page/:num
timezone: Asia/Shanghai

# Markdown Processors
#kramdown:
#  input: GFM
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
