permalink: /:year-:month-:day/:title/

##Site
title: "Know thyself"
author: "liushoukai"
keywords: "博客，Jekyll"
description: "个人博客"
baseurl: ""


links:
  - github: "https://github.com/liushoukai/"

excerpt_separator: "\n\n\n"

analytics:
  provider: google
  google: 
    tracking_id: 'UA-70311570-1' 

defaults:
  - scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post


gems: [jekyll-paginate]
paginate: 3
paginate_path: ":num"
