permalink: /:year-:month-:day/:title/

highlighter: pygments

markdown: kramdown
redcarpet:
  extensions: [
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "strikethrough",
    "superscript",
    "with_toc_data",
    "footnotes",
    "highlight",
    "underline",
    "quote",
    "lax_spacing",
    "prettify",
    "html_toc"
  ]


##Site
title: "Know thyself"
author: "liushoukai"
keywords: "博客，Jekyll"
description: "KAY个人博客"
baseurl: ""


links:
  - github: "https://github.com/liushoukai/"

excerpt_separator: "\n\n\n"

analytics:
  provider: google
  google: 
    tracking_id: 'UA-70311570-1' 

defaults:
  - scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Kay

paginate: 10
paginate_path: ":num"
